name: led_bulb_indicator
description: LED Bulb Indicator
version: 0.0.1
homepage: https://github.com/Terranic/led_bulb_indicator
authors:
  - Constantin Werner

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:

